<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="backgroundMain.jpg" />
    <None Remove="iconTicTacToe.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="backgroundMain.jpg" />
    <Resource Include="iconTicTacToe.jpg" />
  </ItemGroup>

</Project>
